Repository LP23-1A/E-commerce-team-4, pull requests merged in 2024-03, with the labels that each got.

#4 project init
  backend/index.ts
  backend/package-lock.json
  backend/package.json
  backend/tsconfig.json
  frontend/.gitignore
  frontend/README.md
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/src/app/favicon.ico
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: project init

#8 navbar
  frontend/package-lock.json
  frontend/package.json
  frontend/public/Logo.svg
  frontend/public/Vector.svg
  frontend/public/container.svg
  frontend/public/next.svg
  frontend/public/notifications.svg
  frontend/public/vercel.svg
  frontend/src/app/globals.css
  frontend/src/app/page.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/images/Logo.tsx
  frontend/src/images/Noti.tsx
  frontend/src/images/User.tsx
Labels: feature

#18 page 2 hiisen
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/page.tsx
  frontend/src/components/SignUppage2.tsx
  frontend/src/images/ToLeft.tsx
  frontend/tailwind.config.ts
Labels: feature

#23 AsideBar
  frontend/public/board.svg
  frontend/public/income.svg
  frontend/public/product.svg
  frontend/public/settings.svg
  frontend/public/zahialga.svg
  frontend/src/app/page.tsx
  frontend/src/components/AsideBar.tsx
  frontend/src/images/Board.tsx
  frontend/src/images/Income.tsx
  frontend/src/images/Order.tsx
  frontend/src/images/Product.tsx
  frontend/src/images/Settings.tsx
Labels: feature

#35 order detail
  backend/src/router/product.ts
Labels: feature

#41 31 feature auth0
  backend/node_modules/.bin/acorn
  backend/node_modules/.bin/color-support
  backend/node_modules/.bin/mime
  backend/node_modules/.bin/mkdirp
  backend/node_modules/.bin/node-pre-gyp
  backend/node_modules/.bin/nodemon
  backend/node_modules/.bin/nodetouch
  backend/node_modules/.bin/nopt
  backend/node_modules/.bin/rimraf
  backend/node_modules/.bin/semver
  backend/node_modules/.bin/ts-node
  backend/node_modules/.bin/ts-node-cwd
  backend/node_modules/.bin/ts-node-esm
  backend/node_modules/.bin/ts-node-script
  backend/node_modules/.bin/ts-node-transpile-only
  backend/node_modules/.bin/ts-script
  backend/node_modules/.bin/tsc
  backend/node_modules/.bin/tsserver
  backend/node_modules/@mapbox/node-pre-gyp/node_modules/.bin/nopt
  backend/node_modules/@mapbox/node-pre-gyp/node_modules/.bin/nopt.cmd
  backend/node_modules/@mapbox/node-pre-gyp/node_modules/.bin/nopt.ps1
  backend/node_modules/make-dir/node_modules/.bin/semver
  backend/src/controller/product.ts
  backend/src/router/product.ts
  backend/src/utils/database.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/adminSignup/page.tsx
  frontend/src/app/adminSignupStep/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/components/AuthProvider.tsx
  frontend/src/components/SignUpPage3.tsx
  frontend/src/components/SignUpPage4.tsx
  frontend/src/components/SignUppage1.tsx
  frontend/src/components/SignUppage2.tsx
Labels: feature

#46 OrderDetail
  frontend/src/app/orderDetail/page.tsx
  frontend/src/images/Down.tsx
Labels: feature

#50 loading
  frontend/src/app/page.tsx
  frontend/src/components/Loading.tsx
Labels: feature

#53 bug
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/addProduct/page.tsx
Labels: feature

#57 auth bug
  backend/node_modules/.package-lock.json
  backend/node_modules/@types/bcrypt/LICENSE
  backend/node_modules/@types/bcrypt/README.md
  backend/node_modules/@types/bcrypt/index.d.ts
  backend/node_modules/@types/bcrypt/package.json
  backend/node_modules/@types/jsonwebtoken/LICENSE
  backend/node_modules/@types/jsonwebtoken/README.md
  backend/node_modules/@types/jsonwebtoken/index.d.ts
  backend/node_modules/@types/jsonwebtoken/package.json
  backend/package-lock.json
  backend/package.json
  backend/src/controller/admin.ts
  backend/src/controller/auth.ts
  backend/src/controller/index.ts
  backend/src/index.ts
  backend/src/middleware/encrypt.ts
  backend/src/middleware/index.ts
  backend/src/model/admin.ts
  backend/src/model/auth.ts
  backend/src/router/admin.ts
  backend/src/router/auth.ts
  backend/tsconfig.json
  frontend/src/app/Product/page.tsx
  frontend/src/app/dashboard/[id]/page.tsx
  frontend/src/app/dashboardEmpty/[id]/page.tsx
  frontend/src/app/dashboardEmpty/page.tsx
  frontend/src/components/SignUpPage4.tsx
  frontend/src/components/SignUppage1.tsx
Labels: bug

#60 58 feature connect
  backend/.gitignore
  backend/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
  backend/src/controller/auth.ts
  backend/src/controller/order.ts
  backend/src/index.ts
  backend/src/model/order.ts
  backend/src/router/auth.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/Product/page.tsx
  frontend/src/app/addProduct/page.tsx
  frontend/src/app/adminDashboard/page.tsx
  frontend/src/app/adminSignup/page.tsx
  frontend/src/app/adminSignupStep/page.tsx
  frontend/src/app/dashboard/[id]/page.tsx
  frontend/src/app/income/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/order/page.tsx
  frontend/src/app/orderDetail/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/signupStep/page.tsx
  frontend/src/components/.Tabledata.tsx.swp
  frontend/src/components/AdminContext.tsx
  frontend/src/components/AsideBar.tsx
  frontend/src/components/Carddata.tsx
  frontend/src/components/Chart.tsx
  frontend/src/components/EmptyDashboard.tsx
  frontend/src/components/SignUpPage3.tsx
  frontend/src/components/SignUpPage4.tsx
  frontend/src/components/SignUppage1.tsx
  frontend/src/components/SignUppage2.tsx
  frontend/src/components/Tabledata.tsx
  frontend/src/utils/Sidebar.tsx
  package-lock.json
  package.json
Labels: feature

#63 settingstei bolchihlo
  frontend/src/app/Product/page.tsx
  frontend/src/app/addProduct/page.tsx
  frontend/src/app/adminDashboard/page.tsx
  frontend/src/app/income/page.tsx
  frontend/src/app/order/page.tsx
  frontend/src/app/orderDetail/page.tsx
  frontend/src/app/settings/page.tsx
  frontend/src/images/Check.tsx
Labels: bug

#66 65 bug order detail
  backend/src/controller/order.ts
  frontend/public/Pinecone Logo.svg
  frontend/src/app/Product/page.tsx
  frontend/src/app/order/page.tsx
  frontend/src/app/orderDetail/page.tsx
  frontend/src/components/AdminContext.tsx
  frontend/src/components/AsideBar.tsx
  frontend/src/components/UserOrder.tsx
  frontend/src/images/Applelogo.tsx
  frontend/src/images/Board.tsx
  frontend/src/images/Double.tsx
  frontend/src/images/Down.tsx
  frontend/src/images/Edit.tsx
  frontend/src/images/Noti.tsx
  frontend/src/images/Pineconelogo.tsx
  frontend/src/images/Plus.tsx
  frontend/src/images/Right.tsx
  frontend/src/images/ToLeft.tsx
Labels: bug

#70 barag l
  frontend/src/app/Product/page.tsx
  frontend/src/app/addProduct/page.tsx
  frontend/src/app/adminDashboard/page.tsx
  frontend/src/app/income/page.tsx
  frontend/src/app/order/page.tsx
  frontend/src/app/settings/page.tsx
  frontend/src/components/AsideBar.tsx
  frontend/src/components/Carddata.tsx
  frontend/src/components/Navbar.tsx
Labels: enhancement

#72 fixed bug
  frontend/src/app/income/page.tsx
  frontend/src/components/AsideBar.tsx
Labels: bug

#77 autocomplete
  backend/package-lock.json
  backend/package.json
  frontend/src/app/income/page.tsx
  frontend/src/app/order/page.tsx
  frontend/src/app/settings/page.tsx
  frontend/src/components/EmptyDashboard.tsx
Labels: enhancement

#83 82 bug user
  backend/src/controller/auth.ts
  backend/src/router/auth.ts
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/middleware/page.tsx
  frontend/src/components/AdminContext.tsx
  frontend/src/components/SignUpPage3.tsx
  frontend/src/components/SignUpPage4.tsx
  frontend/src/components/SignUppage1.tsx
  frontend/src/components/SignUppage2.tsx
Labels: bug

#87 became useRef
  frontend/src/app/addProduct/page.tsx
  frontend/src/app/editProduct/page.tsx
  frontend/src/components/Navbar.tsx
Labels: enhancement

#95 dashboard bug zasav
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/admin/dashboard/[id]/page.tsx
  frontend/src/app/middleware/page.tsx
  frontend/src/app/signupStep/page.tsx
  frontend/src/components/Amountpaid.tsx
  frontend/src/components/Carddata.tsx
  frontend/src/components/Chart.tsx
  frontend/src/components/Chartreg.tsx
  frontend/src/components/Order.tsx
  frontend/src/components/User.tsx
  frontend/src/components/index.ts
  package-lock.json
Labels: bug

#94 92 income table
  .DS_Store
  backend/package-lock.json
  backend/package.json
  backend/src/controller/product.ts
  backend/src/index.ts
  backend/src/model/product.ts
  frontend/src/app/admin/income/page.tsx
  frontend/src/app/admin/product/addProduct/page.tsx
  frontend/src/app/admin/product/page.tsx
  frontend/src/app/page.tsx
Labels: enhancement

#99 user navbar footer
  frontend/public/Group.svg
  frontend/public/call.svg
  frontend/public/mail.svg
  frontend/public/save.svg
  frontend/public/trolley.svg
  frontend/public/user.svg
  frontend/src/app/page.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/NavbarUser.tsx
  frontend/src/images/Call.tsx
  frontend/src/images/Down.tsx
  frontend/src/images/Group.tsx
  frontend/src/images/Mail.tsx
  frontend/src/images/Save.tsx
  frontend/src/images/SearchUser.tsx
  frontend/src/images/Trolley.tsx
  frontend/src/images/UserNav.tsx
Labels: feature

#102 101 feature shopping cart
  frontend/public/checklist 1.png
  frontend/public/clock.png
  frontend/public/correct.png
  frontend/public/frame.png
  frontend/src/app/user/dashboard/page.tsx
  frontend/src/app/user/orderComplete/page.tsx
  frontend/src/app/user/purchase/page.tsx
  frontend/src/app/user/shopCart/page.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/NavbarUser.tsx
  frontend/src/components/OrderComplete.tsx
  frontend/src/components/PurchaseCart.tsx
  frontend/src/components/PurchaseField.tsx
  frontend/src/components/ShopCart.tsx
  frontend/src/components/index.ts
  frontend/src/images/CheckList.tsx
  frontend/src/images/Clock.tsx
  frontend/src/images/Correct.tsx
  frontend/src/images/index.ts
Labels: feature

#106 LogIn SignUp ERROR
  frontend/public/error.png
  frontend/src/app/page.tsx
  frontend/src/app/user/errorPage/page.tsx
  frontend/src/app/user/logIn/page.tsx
  frontend/src/app/user/products/page.tsx
  frontend/src/app/user/signUp/page.tsx
  frontend/src/components/NavbarUser.tsx
  frontend/src/components/PathUser.tsx
  frontend/src/components/ProductUser.tsx
  frontend/src/components/ProductUserDetail.tsx
  frontend/src/components/index.ts
  frontend/src/images/Error.tsx
  frontend/src/images/index.ts
Labels: feature

#110 product filter
  frontend/src/app/admin/product/addProduct/page.tsx
  frontend/src/app/admin/product/page.tsx
  frontend/src/app/api/upload-image/route.ts
  frontend/src/app/page.tsx
  frontend/src/components/Aws.tsx
  frontend/src/components/CreateProduct.tsx
  frontend/src/components/CreateProductField.tsx
  frontend/src/components/CreateProductProvider.tsx
  frontend/src/components/ProductTableData.tsx
  frontend/src/components/index.ts
  frontend/src/utils/Rate.tsx
Labels: bug

#111 108 product all page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/admin/income/page.tsx
  frontend/src/app/admin/product/addProduct/page.tsx
  frontend/src/app/admin/product/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/page.tsx
  frontend/src/app/user/errorPage/page.tsx
  frontend/src/app/user/gridProduct/page.tsx
  frontend/src/app/user/shopCart/page.tsx
  frontend/src/app/user/shopLeftSidebar/page.tsx
  frontend/src/app/user/shopList/page.tsx
  frontend/src/components/HomeUser.tsx
  frontend/src/components/NavbarUser.tsx
  frontend/src/components/OrderComplete.tsx
  frontend/src/components/PathUser.tsx
  frontend/src/components/ProductUser.tsx
  frontend/src/components/ProductUserDetail.tsx
  frontend/src/utils/Menu.tsx
Labels: enhancement, feature

#114 113 save notification
  frontend/src/app/user/gridProduct/page.tsx
  frontend/src/app/user/saveList/page.tsx
  frontend/src/app/user/shopLeftSidebar/page.tsx
  frontend/src/app/user/shopList/page.tsx
  frontend/src/components/NavbarUser.tsx
  frontend/src/components/PathUser.tsx
  frontend/src/components/ProductUserDetail.tsx
Labels: enhancement, feature

#117 103 feature product details
  frontend/public/10011 1.png
  frontend/public/Ellipse 24.svg
  frontend/public/Ellipse 25.svg
  frontend/public/Ellipse 26.svg
  frontend/public/Group 235.svg
  frontend/public/Rectangle 134.png
  frontend/public/Rectangle 136.png
  frontend/public/Rectangle 137.png
  frontend/public/Rectangle 138.png
  frontend/public/akar-icons_arrow-up.svg
  frontend/public/emptyStar.svg
  frontend/public/fullStar.svg
  frontend/public/image 1165.png
  frontend/public/image 1173.png
  frontend/public/uil_heart-alt.svg
  frontend/src/app/user/productDetail/page.tsx
  frontend/src/images/BlueDot.tsx
  frontend/src/images/EmptyStar.tsx
  frontend/src/images/FullStar.tsx
  frontend/src/images/Heart.tsx
  frontend/src/images/OrangeDot.tsx
  frontend/src/images/PinkDot.tsx
  frontend/src/images/Rectangle1.tsx
  frontend/src/images/Rectangle2.tsx
  frontend/src/images/Rectangle3.tsx
  frontend/src/images/Rectangle4.tsx
  frontend/src/images/RightArrow.tsx
  frontend/src/images/cam3.png
Labels: feature

#118 user dashboard done
  frontend/public/24-hours-support 1.svg
  frontend/public/Group.svg
  frontend/public/cashback 1.svg
  frontend/public/premium-quality 1.svg
  frontend/public/sandl.png
  frontend/public/sofa promotional header.svg
  frontend/src/app/user/dashboard/page.tsx
  frontend/src/components/Carousel.tsx
  frontend/src/components/New.tsx
  frontend/src/components/Ontsloh.tsx
  frontend/src/components/Service.tsx
  frontend/src/components/index.ts
  frontend/src/images/Car.tsx
  frontend/src/images/Cashback.tsx
  frontend/src/images/Mebel.tsx
  frontend/src/images/Premium.tsx
  frontend/src/images/Sndal.tsx
  frontend/src/images/Support.tsx
  frontend/src/images/index.ts
Labels: feature

#119 112 feature user order
  backend/src/controller/order.ts
  backend/src/controller/product.ts
  backend/src/model/order.ts
  backend/src/router/order.ts
  backend/src/router/product.ts
  frontend/src/app/admin/income/page.tsx
  frontend/src/app/admin/order/orderDetail/page.tsx
  frontend/src/app/admin/product/page.tsx
  frontend/src/app/api/upload-image/route.ts
  frontend/src/app/layout.tsx
  frontend/src/app/user/purchase/page.tsx
  frontend/src/app/user/shopCart/page.tsx
  frontend/src/app/user/shopList/page.tsx
  frontend/src/components/AsideBar.tsx
  frontend/src/components/CreateProduct.tsx
  frontend/src/components/CreateProductProvider.tsx
  frontend/src/components/NavbarUser.tsx
  frontend/src/components/OrderFinish.tsx
  frontend/src/components/PathUser.tsx
  frontend/src/components/ProductTableData.tsx
  frontend/src/components/ProductUserDetail.tsx
  frontend/src/components/PurchaseCart.tsx
  frontend/src/components/PurchaseField.tsx
  frontend/src/components/ShopCart.tsx
  frontend/src/components/UserOrderProvider.tsx
  frontend/src/components/index.ts
Labels: feature

#121 116 feature user signup login
  backend/src/controller/auth.ts
  backend/src/model/auth.ts
  backend/src/model/order.ts
  backend/src/router/auth.ts
  frontend/src/app/user/logIn/page.tsx
  frontend/src/app/user/signUp/page.tsx
  frontend/src/components/NavbarUser.tsx
  frontend/src/components/New.tsx
  frontend/src/components/Ontsloh.tsx
  frontend/src/components/ProductUserDetail.tsx
Labels: enhancement, feature

#126 some style
  frontend/src/app/admin/dashboard/[id]/page.tsx
  frontend/src/app/admin/settings/page.tsx
  frontend/src/app/user/shopCart/page.tsx
  frontend/src/app/user/signUp/page.tsx
  frontend/src/components/AdminOrderTable.tsx
Labels: bug

#125 svg stroke width ynzlah
  frontend/src/app/user/productDetail/page.tsx
  frontend/src/images/RightArrow.tsx
  frontend/src/images/SaveProduct.tsx
  frontend/src/images/SearchProduct.tsx
  frontend/src/images/SearchUser.tsx
  frontend/src/images/Star.tsx
  frontend/src/images/Trolley.tsx
  frontend/src/images/TrolleyProduct.tsx
  frontend/src/images/Up.tsx
  frontend/src/images/UserNav.tsx
Labels: bug

#127 fixed
  frontend/public/deliver.svg
  frontend/src/app/admin/order/orderDetail/page.tsx
  frontend/src/app/admin/product/addProduct/page.tsx
  frontend/src/app/admin/product/page.tsx
  frontend/src/components/AsideBar.tsx
  frontend/src/components/CreateProduct.tsx
  frontend/src/components/CreateProductField.tsx
  frontend/src/components/Orderfilter.tsx
  frontend/src/components/ProductTableData.tsx
  frontend/src/images/Deliver.tsx
  frontend/src/images/index.ts
Labels: bug

#131 129 bug fixed code
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/admin/income/page.tsx
  frontend/src/app/admin/signup/page.tsx
  frontend/src/app/middleware/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/signupStep/page.tsx
  frontend/src/app/user/dashboard/page.tsx
  frontend/src/app/user/gridProduct/page.tsx
  frontend/src/app/user/login/page.tsx
  frontend/src/app/user/productDetail/page.tsx
  frontend/src/app/user/shopCart/page.tsx
  frontend/src/app/user/shopLeftSidebar/page.tsx
  frontend/src/app/user/shopList/page.tsx
  frontend/src/app/user/signUp/page.tsx
  frontend/src/components/CreateProduct.tsx
  frontend/src/components/DeleteBtn.tsx
  frontend/src/components/NavbarUser.tsx
  frontend/src/components/New.tsx
  frontend/src/components/Ontsloh.tsx
  frontend/src/components/PathUser.tsx
  frontend/src/components/ProductUserDetail.tsx
  frontend/src/components/UserOrderProvider.tsx
  frontend/src/images/Cashback.tsx
  frontend/src/images/Delete.tsx
  frontend/src/images/Mebel.tsx
  frontend/src/images/Premium.tsx
  frontend/src/images/RightArrow.tsx
  frontend/src/images/SaveProduct.tsx
  frontend/src/images/SearchProduct.tsx
  frontend/src/images/SearchUser.tsx
  frontend/src/images/Star.tsx
  frontend/src/images/Support.tsx
  frontend/src/images/Trolley.tsx
  frontend/src/images/TrolleyProduct.tsx
  frontend/src/images/Up.tsx
  frontend/src/images/UserNav.tsx
Labels: bug

#133 fixed
  frontend/src/app/user/dashboard/page.tsx
  frontend/src/components/Ontsloh.tsx
Labels: bug
